### ISSUE TITLE
How to Compile IMY.kt file?

### ISSUE THREAD

**Issue by min2222** [talestra/talestrakt#1]
Hello I am trying to compile IMY.kt to decompress the .imy file in a game called Criminal Girls, but I keep getting an error. How do I fix it? 
also here is error log : https://pastebin.com/3U11F2GD

**Comment by soywiz** [comment]
Thanks for reporting. It has been a while, but let me check if I can fix that

**Comment by soywiz** [comment]
IntelliJ probably replaced a string at some point, and that prevented the format from being detected. I have also moved all the code to an `@old` folder since unfortunately I'm not supporting this right now. Maybe at some point in the future in a holidays or something just for fun. You can try to the `IMY.kt` and try to create your own code to extract the images with the latest version of KorIM published into central. With luck with that!
